apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: webapp-color
  name: webapp-color
spec:
  containers:
  - image: kodekloud/webapp-color
    imagePullPolicy: IfNotPresent
    name: webapp-color
    env:
    - name: APP_COLOR
#      value: "green"
      valueFrom:
        configMapKeyRef:
          name: webapp-config-map
          key: APP_COLOR
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
