apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fruit-service
  name: fruit-service
spec:
  containers:
  - image: linuxacademycontent/legacy-fruit-service:1
    name: fruit-service
  - image: haproxy:1.7
    name: haproxy-ambassador
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/local/etc/haproxy
  volumes:
  - name: config-volume
    configMap:
      name: fruit-service-ambassador-config
