apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p1
  name: my-secret-pod
spec:
  containers:
  - image: busybox
    name: myapp-container
    command: ['sh', '-c', "echo Hello, World! pass is  ${MY_PASSWORD} && sleep 3600"]
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: myKey
