apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: cj1
  name: cj1
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: cj1
        spec:
          containers:
          - image: ubuntu
            name: cj1
            resources: {}
            command: ["/bin/sh"]
            args: ["-c","date"]
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
