apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: j1
  name: j1
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: j1
    spec:
      containers:
      - image: nginx
        name: j1
        resources: {}
      restartPolicy: OnFailure
status: {}
