apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: throw-dice-job
  name: throw-dice-job
spec:
  completions: 3
  parallelism: 3
  backoffLimit: 25 # This is so the job does not quit before it succeeds.
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: throw-dice-job
    spec:
      containers:
      - image: kodekloud/throw-dice
        name: throw-dice-job
        resources: {}
      restartPolicy: OnFailure
status: {}
